### PR TITLE
Upgrade Binaryen

### PR DESCRIPTION
**Pull request by phated**
We need to upgrade binaryen (and we should track this more regularly) for a bunch of fixes that we need to possibly get this to work on Windows.

I've begun upstreaming those changes, but our bindings break when pulling them into this project. This seems to be due to breaking changes that happened since we wired up our submodules. I tracked one of the changes back to https://github.com/WebAssembly/binaryen/commit/2841eddaabc7a5e24517e043a1aab8adc6d5c1e4 - but I'm going to need @ospencer's expertise to get things actually working.

This is a blocker on my further work to get Windows builds working.

### CODE REVIEW

**Comment by phated** [comment]
You might need `git submodule sync --recursive` to sync the new submodule remote

**Comment by phated** [comment]
And the CI should fail with the errors I'm seeing.

**Comment by ospencer** [comment]
Oh yup, I'll hit this in a bit.

**Review by ospencer — APPROVED** [review]

**Comment by phated** [comment]
We can't upgrade Binaryen for the JS bindings because of this https://github.com/WebAssembly/binaryen/pull/2990#issuecomment-716956627

**Comment by phated** [comment]
Superseded by #75

**Pull request closed without merging**
