### PR TITLE
Bump to Binaryen 98

### PR DESCRIPTION
**Pull request by ospencer**
I tested this locally with the Grain compiler and all of the tests pass 👍 

@phated I don't know what's up with the formatter, but I can't get it to auto promote.

### CODE REVIEW

**Review by phated — APPROVED** [review]
@ospencer looks good! This really needs to be formatted in a semantic commit that explains what you removed/changed when squashed-merged. :shipit: 

(I'd like to get the CI scripts fixed up before we cut the opam release, so I don't need to babysit it so much)

**Comment by ospencer** [comment]
@phated I don't know what's up with the opam workflow... is there any chance this is also broken for esy but the cache is saving it?

**Comment by phated** [comment]
Definitely seems like something is wrong. I don't have time to debug atm

**Review by phated — CHANGES_REQUESTED** [review]
@ospencer I just realized that you never pulled down the binaryen.js build and jammed it in this PR.

I believe this version is going to be incompatible with jsoo, so we might need to finally add the es5 build to our build server

**Comment by ospencer** [comment]
Confirmed that it's incompatible.

**Review by phated — APPROVED** [review]
:approved: but please fix up the conventional commit so opam people will see the actual removed/changed methods too

**Pull request merged**
