### PR TITLE
feat!: upgrade to binaryen v95 & vendor prebuilt artifacts

### PR DESCRIPTION
**Pull request by phated**
This applies a bunch of the lessons I learned around vendoring prebuilt artifacts and linking them into our bindings. However, I only bumped binaryen to v95 (which was a few days after the commit our submodule was tied to). Another binaryen bump will come once they release v99 so we can vendor from master again (ref #32).

This will get us Windows support and will significantly reduce build times, with the caveat that the end-user systems need to be close to the systems we built the artifacts on (GH Actions CI). In the future, we might want to have a fallback to build from source, or some other strategy to avoid that caveat. This also increases the download size significantly.

One of the big things I'm scared about with this is breaking @ng-marcus' fancy new ARM Mac.

### CODE REVIEW

**Comment by phated** [comment]
I believe the Windows Esy tests will fail because it doesn't know where nodejs is in the path. I'll probably have to tweak a workflow or the package.json before landings this.

**Review by ospencer — APPROVED** [review]
I think this is good. If it turns out we've got a bunch of problems, we can set up the fallback to build from source.

Well done! 🎊

**Comment by ng-marcus** [comment]
I think this helps with the fancy new ARM Mac :)

I'm currently installing everything from binaries which Rosetta transpiles and runs.  So NodeJs for example I download the installer and it works great.  Trying to use NVM fails because it compiles, and then I'm in a mixed world of the ARM tools trying to build ARM binaries.  So currently I can't get Grain to compile locally, I'm dependent on compiling it on an Intel machine and copying it over to run under emulation.

So for the moment at least, prebuild artifacts definitely don't hinder, and will probably help. I'll try this out today

**Comment by phated** [comment]
@ospencer I've opened https://github.com/esy/esy/issues/1232 in relation to our failing Windows tests within the esy sandbox. However, for the time being, I've just disabled our JS tests on all Windows environments.

I think we can ship this tonight.

**Comment by ospencer** [comment]
I think that's a fine solution for now!

**Pull request merged**
