### PR TITLE
opam: Remove unnecessary constraints

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Tested locally, they all work fine.

### CODE REVIEW

**Comment by phated** [comment]
If you also update the package.json and esy.lock, you'll notice the failures on windows. We're still waiting for a fix.

**Comment by phated** [comment]
@kit-ty-kate this actually also broke for me on MacOS. I just pushed the esy changes to show you that it's broken and we shouldn't remove these constraints until the fixes can be made upstream.

**Comment by kit-ty-kate** [comment]
> @kit-ty-kate this actually also broke for me on MacOS

Really? My local testing machine is macOS and was working perfectly fine

**Comment by phated** [comment]
The error seems to be happening on `dune install` inside of one (all?) of the JSOO packages. It is trying to call opam, which isn't available in an esy sandbox.

**Comment by phated** [comment]
This is the error (I'm assuming we'll see this same thing in CI soon):
```bash
$ esy
info esy 0.6.13-dev (using package.json)
info fetching: done                                                                                     
info installing: done                                                                                              
info building @opam/js_of_ocaml-ppx@opam:4.0.0@bca7f5ce
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/js_of_ocaml-ppx@opam:4.0.0
    # esy-build-package: pwd: /Users/phated/.esy/3/b/opam__s__js__of__ocaml_ppx-opam__c__4.0.0-eb663ec4
    # esy-build-package: running: 'dune' 'build' '-p' 'js_of_ocaml-ppx' '-j' '4' '--promote-install-files=false' '@install'
    (cd tools/version && /Users/phated/.esy/3_________________________________________________________________/i/ocaml-4.13.1000-8a7a040f/bin/ocaml -I +compiler-libs /Users/phated/.esy/3/b/opam__s__js__of__ocaml_ppx-opam__c__4.0.0-eb663ec4/_build/.dune/default/tools/version/dune.ml)
    fatal: not a git repository (or any of the parent directories): .git
    # esy-build-package: running: 'dune' 'install' '-p' 'js_of_ocaml-ppx' '--create-install-files' 'js_of_ocaml-ppx'
    Error: Program opam not found in the tree or in PATH
    error: command failed: 'dune' 'install' '-p' 'js_of_ocaml-ppx' '--create-install-files' 'js_of_ocaml-ppx' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @opam/js_of_ocaml-ppx@opam:4.0.0
esy: exiting due to errors above
```

**Comment by kit-ty-kate** [comment]
That sounds like https://github.com/ocaml/dune/issues/5455. It looks like esy maintainers should remove dune from their repository.

Then my first commit was fine on its own given only the opam file was modified.

**Comment by phated** [comment]
> It looks like esy maintainers should remove dune 3 from their repository.

There isn't an esy repository.

> Then my first commit was fine on its own given only the opam file was modified.

You can install binaryen.ml with `@opam/binaryen` or `@grain/binaryen.ml` and I don't want to vary the dependencies people will get because then you can't use esy to get the `@opam/binaryen` version.

Please 🙏 leave these constraints in place until we can actually fix the ecosystem.

**Comment by kit-ty-kate** [comment]
> There isn't an esy repository.

I meant this: https://github.com/esy-ocaml/esy-opam-override

**Comment by phated** [comment]
> I meant this: https://github.com/esy-ocaml/esy-opam-override

The esy overrides project is not meant to **remove** a package from opam, it is mainly just to apply a patch to an opam file on a few opam packages that likely can't/won't be changed upstream. The problems with dune 3 seem to be much deeper.

**Comment by phated** [comment]
Closing this, as I'm tracking the dune 3 bugs that cause it to break if opam is not available on the path. We'll open the constraints as soon as that is fixed and released!

**Pull request closed without merging**
